### ISSUE TITLE
Feature: syntax highlight code fences

### ISSUE THREAD

**Issue by nathany** [MikeMcQuaid/GitHub-Markdown.tmbundle#4]
Thanks for the bundle. One nice feature of the markdown package for Atom is that it syntax highlights code fenced blocks appropriately. Is that possible in TextMate 2?

![syntax](https://cloud.githubusercontent.com/assets/4566/12874553/1499d89a-cd93-11e5-8435-a76a9560d259.png)

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/mikemcquaid/GitHub-Markdown.tmbundle/commit/eb2ff4d2a52173a81bb28dfe11827af221ab3ab6. Languages need to be individually configured so I haven't added them all but feel free to submit PRs like https://github.com/mikemcquaid/GitHub-Markdown.tmbundle/commit/eb2ff4d2a52173a81bb28dfe11827af221ab3ab6 to add any more you use (the language names/aliases are listed in https://github.com/github/linguist/blob/master/lib/linguist/languages.yml)

**Comment by nathany** [comment]
Thanks.

It seems to be doing something odd though, with the font not switching back to Helvetica and the colours of regular text is green like strings. 

I'm viewing the contents of this file.
https://raw.githubusercontent.com/RobotsAndPencils/buford/master/README.md

My theme happens to be Tomorrow Night if that matters.

**Comment by MikeMcQuaid** [comment]
@nathany My mistake when copy-pasting; should be fixed in https://github.com/mikemcquaid/GitHub-Markdown.tmbundle/commit/5dc814de48150304bc76c2450c58224a8a4654a1

**Comment by nathany** [comment]
That looks much better. Thanks!
