### ISSUE TITLE
Configure the font

### ISSUE THREAD

**Issue by nathany** [MikeMcQuaid/GitHub-Markdown.tmbundle#5]
How does one pick the font?

Like others, I'm [no fan of Baskerville](https://github.com/hiltmon/hiltons-bundle) as the default header font. But I also don't care for Helvetica much. I'd prefer to just keep the mono-space font that I use elsewhere.

I saw a similar sentiment in the forums. Is there a way to configure it?

**Comment by sanssecours** [comment]
Hi Nathan,

to change the font:
1. Open  `Bundles→Edit Bundles…` (<kbd>^</kbd>+<kbd>⌥</kbd>+<kbd>⌘</kbd>+<kbd>B</kbd>)
2. Select `Markdown (GitHub)`
3. Go to `Settings→Font Name and Size`
4. Change the font and save your changes (<kbd>⌘</kbd>+<kbd>S</kbd>). I use `Seravek` in the screenshot below. Since you mentioned you want a monospaced font, something like `Menlo` or [`Ubuntu Mono`](http://font.ubuntu.com) might be a better choice for you.
   
   <img width="993" alt="markdown" src="https://cloud.githubusercontent.com/assets/691989/12880874/4030a59e-ce45-11e5-9326-6feef063a913.png">
5. Restart TextMate (<kbd>^</kbd>+<kbd>⌘</kbd>+<kbd>Q</kbd>)

**Comment by nathany** [comment]
Thanks.

**Comment by MikeMcQuaid** [comment]
Seems this is resolved? Thanks for the help, @sanssecours!

**Comment by nathany** [comment]
It seems the code and text is still a different font. I tried making the Raw text use Menlo as well.

To be honest, I'm not a huge fan of all this fancy font stuff. I just want to inherit the font I decided on for AsciiDoc and everything else. 

While the bundle makes it easy to change, it's also kind've a pain. Now that I've modified the bundle, a git pull is going to fail and I'll need to stash/redo my changes to update.

**Comment by MikeMcQuaid** [comment]
@nathany Thanks for the feedback. I don't think there's an easy way to make this more configurable but I'll take what you've said on consideration and consider changing this if more users chime in and dislike it.

**Comment by MikeMcQuaid** [comment]
I split these into another bundle: https://github.com/mikemcquaid/GitHub-Markdown-Font-Settings.tmbundle

**Comment by nathany** [comment]
Nice idea. Thanks.
